### ISSUE TITLE
unrendered equation 

### ISSUE THREAD

**Issue by delatorrena2016** [blaisewang/img2latex-mathpix#104]
I downloaded the recent 0.7.7 Image2LaTex-windows, I got the OCR API Keys. For some reason, once I took the caption with Window's snipping tool, Image2Latex (I2L) does not detect it. I have to open I2L after i took the caption. The real problem is that I'm not getting the rendered equation. It does appear in the clipboard image, and that is it.

**Comment by delatorrena2016** [comment]
Descargué la versión anterior, y ya puedo utilizar la aplicación, estoy agradecido.

**Comment by blaisewang** [comment]
The rendered equation is only a helper for users to verify the results. Sometimes the latex cannot be rendered due to incompatible format with new API.
