### ISSUE TITLE
[Bug] Mathpix OCR API now costs?

### ISSUE THREAD

**Issue by the-raspberry-pi-guy** [blaisewang/img2latex-mathpix#108]
Not really a bug on any of this software, but just came back to this repo to reinstall on a new Mac (I last used this project a year ago), and tried to log back into my Mathpix OCR API account. I noticed that they had made some changes to the sign in and it now looks like the OCR costs money, even within the previous 1000 free queries? Is this correct or have I misunderstood something?

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/5570173/115470237-e7232400-a22d-11eb-8360-acc96a5f5779.png">

**Comment by blaisewang** [comment]
If my understanding is correct, mathpix will start to charge after the first 1000 requests as it stated $0.004/request (1-100K requests). For further confirmation, maybe you need to contact mathpix customer support.

**Comment by the-raspberry-pi-guy** [comment]
It turns out that there was an account mismatch for me that Mathpix support resolved. Looks like the first 1000 requests are still free - sorry for any confusion and thanks for the great OS project! :))
