### ISSUE TITLE
Can't access settings after first configuration

### ISSUE THREAD

**Issue by ghost** [blaisewang/img2latex-mathpix#111]
**Describe the bug**
I configured the application with the API generated on MathPix.
After closing that window, I got into the main window which allows to paste images.
However, on subsequent runs, I can't find a way to open the setting window again.
The obvious reason would be to see the request count and change default style for latex.
Is there a shortcut I am missing?

I am on ArchLinux, downloaded from releases..

**Comment by blaisewang** [comment]
sorry for the late reply, try right-clicking the app window
