### ISSUE TITLE
Qt: Session management error: Could not open network socket

### ISSUE THREAD

**Issue by alpereninci** [blaisewang/img2latex-mathpix#112]
When I try to run math2pix-snipping-tool it gives this error. How can I solve the problem

Qt: Session management error: Could not open network socket
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.195\" (uid=1000 pid=6378 comm=\"mathpix-snipping-tool \" label=\"snap.mathpix-snipping-tool.mathpix-snipping-tool (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=930 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.195\" (uid=1000 pid=6378 comm=\"mathpix-snipping-tool \" label=\"snap.mathpix-snipping-tool.mathpix-snipping-tool (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=930 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
Killed

**Comment by blaisewang** [comment]
mathpix-snipping-tool is not developed by me. please reach out mathpix via support@mathpix.com
