### ISSUE TITLE
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found

### ISSUE THREAD

**Issue by xiesp** [blaisewang/img2latex-mathpix#113]
可以请假一下吗，Idea一运行就这样，google很久都不知道怎么解决，不好意思第一次接触JavaFX，不知道是不是哪里没搞对？

- JDK:使用 `jdk_setup.sh`下载的，已配置好，JDK14
- gradle:6.6.1,编译无问题

PS,能不能写个如何初始化运行的说明：）

**Comment by blaisewang** [comment]
正常的使用的话直接去 GitHub release 下载构建好的二进制就好了，https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.7.7

**Comment by xiesp** [comment]
> 正常的使用的话直接去 GitHub release 下载构建好的二进制就好了，https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.7.7

是这样的，我想在这个项目里面集成一下有道的OCR功能，所以想要运行编译一下：）

**Comment by blaisewang** [comment]
> Idea一运行就这样

idea 运行时发生了什么？build 没问题的，代码中没有红色的的标记话说明依赖已经下载完了，idea 右边选择 run 就好了

**Comment by xiesp** [comment]
> > Idea一运行就这样
> 
> idea 运行时发生了什么？build 没问题的，代码中没有红色的的标记话说明依赖已经下载完了，idea 右边选择 run 就好了

OK,谢谢，我研究下，我还以为除了JDK14还有其他别的依赖。谢谢

**Comment by blaisewang** [comment]
javafx 不是一个好的选择，会踩很多坑，建议考虑一下其他语言，比如 electron？

**Comment by xiesp** [comment]
> javafx 不是一个好的选择，会踩很多坑，建议考虑一下其他语言，比如 electron？

我已经找到原因了，是ubuntu下缺少libprism_sw.so包导致的，还不少，但是没够google到解决办法，stackoverflow上也不少人遇到过。感谢您的建议，我也打算搞一下electron,谢谢
