### ISSUE TITLE
[Bug]To prevent automated abuse we charge a one-time non-refundable setup fee of $19.99.

### ISSUE THREAD

**Issue by ma3252788** [blaisewang/img2latex-mathpix#119]
**Describe the bug**

Is it unusable now? I think there will be a charge

**Comment by blaisewang** [comment]
I guess Mathpix changed their policy to prevent abuse of their API. This project will no longer be maintained in the foreseen future as I am quite busy with my work, and I am no longer a student any more, so subscribe to their authors' product is more feasible.
