### ISSUE TITLE
win10安装出现错误

### ISSUE THREAD

**Issue by yaohong772** [blaisewang/img2latex-mathpix#12]
win10下单击gradlew出现如下错误：
* What went wrong:
java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

**Comment by blaisewang** [comment]
如果我没有理解错，你是想二次开发对吗？如果只是使用的话请到 [Releases](https://github.com/blaisewang/img2latex-mathpix/releases) 页面下载最新的版本即可。这个错误的原因应该是你还在用JDK 8，这个项目用到了一些JDK 9、10的新特性，此外compile plugin也只支持JDK 11，所以最低安装版本是11。

**Comment by yaohong772** [comment]
谢谢您的建议，我可以运行了，但是不懂怎么使用，运行 gradlew .bat  出现如下界面




如何才能实现demon中的图形界面呢？




———————————————————   
姚 红
北京航空航天大学 物理科学与核能工程学院
北京市海淀区学院路37号 邮编：100083


Hong Yao
School of Physics and Nuclear Energy Engineering, Beihang University 
No.37 Xueyuan Road, HaiDian distinct, Beijing,100083
Email:yaohong@edu.buaa.cn
Tel:18593231695
———————————————————
在2019年11月9日 21:33，Blaise Wang<notifications@github.com> 写道：

如果我没有理解错，你是想二次开发对吗？如果只是使用的话请到 Release 页面下载最新的版本即可。这个错误的原因应该是你还在用JDK 8，这个项目用到了一些JDK 9、10的新特性，此外compile plugin也只支持JDK 11，所以最低安装版本是11。

**Comment by blaisewang** [comment]
直接回复邮件的话是看不到截图的。请读中文版使用说明，里面有如何运行。

**Comment by yaohong772** [comment]
目前到这个地步了，我不会java语言，有些看不懂
![image](https://user-images.githubusercontent.com/57561655/68532057-29b3b200-0354-11ea-9dbe-6c7a838e6198.png)
你的中文教程中我没看明白如何才能运行图形界面
![image](https://user-images.githubusercontent.com/57561655/68532080-5ec00480-0354-11ea-849e-8352eee01665.png)

**Comment by blaisewang** [comment]
你需要下载 releases 页面的程序而不是代码，第一个回复已经附上了链接。下载完成后点击 `bin/Image2Latex.bat` 运行。

**Comment by yaohong772** [comment]
好的，我找到了，谢谢啦。早些休息，晚安 ！！！


———————————————————   
姚 红
北京航空航天大学 物理科学与核能工程学院
北京市海淀区学院路37号 邮编：100083


Hong Yao
School of Physics and Nuclear Energy Engineering, Beihang University 
No.37 Xueyuan Road, HaiDian distinct, Beijing,100083
Email:yaohong@edu.buaa.cn
Tel:18593231695
———————————————————
在2019年11月9日 21:33，Blaise Wang<notifications@github.com> 写道：

如果我没有理解错，你是想二次开发对吗？如果只是使用的话请到 Release 页面下载最新的版本即可。这个错误的原因应该是你还在用JDK 8，这个项目用到了一些JDK 9、10的新特性，此外compile plugin也只支持JDK 11，所以最低安装版本是11。

**Comment by yaohong772** [comment]
1.运行Image2LaTeX.bat会同时打开CMD窗口，有什么办法启动时不打开CMD窗口？
2.Image2LaTeX在win10下可以自定义快捷键截图吗，截完图能自动将Image2LaTeX窗口放在桌面最前面。

**Comment by blaisewang** [comment]
1. 暂时不行
2. 不可以
