### ISSUE TITLE
don't find some files in this subject？

### ISSUE THREAD

**Issue by Dr-Zhou** [blaisewang/img2latex-mathpix#14]
Sorry。I don't find the file named "Image2LaTeX.bat" in your subject. Where do I find it ?

**Comment by blaisewang** [comment]
Hi, [download](https://github.com/blaisewang/img2latex-mathpix/releases) and extract the zip file first. Then you should be able to see `Image2LaTeX.bat` under `bin` folder.

**Comment by Dr-Zhou** [comment]
Following is my directory. I don't find it.
![QMU _L5@MQQLJCGVF$A7(EF](https://user-images.githubusercontent.com/26479520/69913930-01adff00-1479-11ea-916c-76a91af6e8ad.png)

**Comment by blaisewang** [comment]
This is the source code, not the released zip file. [Download link](https://github.com/blaisewang/img2latex-mathpix/releases)

**Comment by Dr-Zhou** [comment]
Thank you。




------------------&nbsp;Original&nbsp;------------------

**Comment by Dr-Zhou** [comment]
The app shows invalid credential。what wrong with this? Where do I get the AppID and key?

**Comment by happyTonakai** [comment]
@Dr-Zhou Sign up at here [MathpixOCR dashboard](https://dashboard.mathpix.com/)
You need a valid credit card for registration.

**Comment by qinshuaibo** [comment]
> Following is my directory. I don't find it.
> ![QMU _L5@MQQLJCGVF$A7(EF](https://user-images.githubusercontent.com/26479520/69913930-01adff00-1479-11ea-916c-76a91af6e8ad.png)
你好，我从github上下载之后也遇到了这个问题，找不到bat文件，你是怎么解决的呢

**Comment by happyTonakai** [comment]
@qinshuaibo 下载 release 中的 `Image2LaTeX-0.2.0-windows.zip`，65.4 MB 的那个，不要下载 Source code

**Comment by Dr-Zhou** [comment]
Because this isn't the downlink. The downlink  is https://github.com/blaisewang/img2latex-mathpix/releases

**Comment by Dr-Zhou** [comment]
> @Dr-Zhou Sign up at here [MathpixOCR dashboard](https://dashboard.mathpix.com/)
> You need a valid credit card for registration.

T try it

**Comment by qinshuaibo** [comment]
> @qinshuaibo 下载 release 中的 `Image2LaTeX-0.2.0-windows.zip`，65.4 MB 的那个，不要下载 Source code

谢啦，找到了，可惜注册需要信用卡。。。。。
