### ISSUE TITLE
Win10 下运行时任务栏中没有对应的窗口

### ISSUE THREAD

**Issue by happyTonakai** [blaisewang/img2latex-mathpix#15]
运行 `Image2LaTeX.bat` 后只会出现一个 cmd 窗口，Image2LaTeX 的主窗口并不会显示在任务栏中，这样在运行全屏软件（pdf阅读软件或者写论文的编辑器）时都无法快速找到 Image2LaTeX

我使用双屏的话感觉还好，但是使用单个显示器的同学可能会很不方便吧。

如果没有任务栏图标的话，能否在截图成功后自动显示 Image2LaTex 的主窗口，方便点击 Submit

**Comment by blaisewang** [comment]
我之前在虚拟机测试以及其他同学反馈图标在Windows 10是会显示在任务栏右下角的，Windows的机制是默认隐藏在二级菜单中，可能需要手动拖出来。图标默认是蓝色的，长[这样](https://github.com/blaisewang/img2latex-mathpix/blob/master/src/main/resources/icon-windows.png)。如果没有找到的话，需要提供更详细的信息来帮助复现这个问题。

第二个目前实现不了的原因是Java 应用运行在JVM虚拟机中，目前已知的解决方法并不能跨平台全局监听用户的按键操作。至少我还没发现一个行之有效的方法，比如[JNativeHook](https://github.com/kwhat/jnativehook) ，上一次 Release 的时间是2017年1月，在我使用的操作系统macos Catalina上无法使用。如果有人可以实现这个功能欢迎 [Pull Request](https://github.com/blaisewang/img2latex-mathpix/pulls)。

**Comment by happyTonakai** [comment]
找到了对应的图标。

不过我说的不是任务栏右下角通知区域的小图标，而是任务栏中可以通过 `Alt+Tab` 进行快速切换的窗口。

如果难以实现的话使用起来会比较麻烦，不过可以通过右下角图标唤出的话也能够正常使用。

**Comment by blaisewang** [comment]
那这个feature可以作为一个可设置选项，随同下一个版本中发布，不过下一个版本不一定什么时间发。

**Comment by Mrlong12** [comment]
请问你们是在哪里下载的.zip包，github上并没有给连接啊，我找不到你们在哪里发布的.
