### ISSUE TITLE
Failed to Execute : Error Occurred

### ISSUE THREAD

**Issue by sdogsq** [blaisewang/img2latex-mathpix#20]
I tried to run D:\Image2LaTeX-windows\bin\Image2LaTeX.bat  on Windows 10. And terminal shows:

Error occurred during initialization of VM
Unable to load native library: Can't find dependent libraries

Now I don't know what to do next. Could you please help me ? Thx.

**Comment by blaisewang** [comment]
Currently, I do not have a Windows OS PC. So far, you are the only one to report this issue. I need more information to fix this.
