### ISSUE TITLE
[Mac] Discrete graphics waken during usage

### ISSUE THREAD

**Issue by hamkz** [blaisewang/img2latex-mathpix#22]
Just asking, do we really need to switch to discrete graphics when using img2latex? I'd prefer integrated graphics if possible, as it uses lower power and makes less fan noise.

P.S. I am using 2018 15 inch macbook pro

**Comment by blaisewang** [comment]
Will implement this proposal according to [this post](https://bugs.openjdk.java.net/browse/JDK-8169592) in next release. But not sure if the solution will work.

**Comment by hamkz** [comment]
> Will implement this proposal according to [this post](https://bugs.openjdk.java.net/browse/JDK-8169592) in next release. But not sure if the solution will work.

Sounds great! Thanks a lot!

**Comment by blaisewang** [comment]
> > Will implement this proposal according to [this post](https://bugs.openjdk.java.net/browse/JDK-8169592) in next release. But not sure if the solution will work.
> 
> Sounds great! Thanks a lot!

Hi, sorry for the late reply, I am quite busy with my job recently. The solution to fix this issue doesn't apply to this app as there is no `Info.plist` in the project. As stated in the [FQA](https://github.com/blaisewang/img2latex-mathpix#fqa) section, the native self-contained executable application will be released after the GA release of Java 14 in 2020. At that time, I will try to fix this issue by this solution.

**Comment by blaisewang** [comment]
> Hi, sorry for the late reply, I am quite busy with my job recently. The solution to fix this issue doesn't apply to this app as there is no `Info.plist` in the project. As stated in the [FQA](https://github.com/blaisewang/img2latex-mathpix#fqa) section, the native self-contained executable application will be released after the GA release of Java 14 in 2020. At that time, I will try to fix this issue by this solution.

As of [0.3.1](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.3.1) release, macOS app bundle is provided. However, after testing with gfxCardStatus and above hypothetical solution, this issue will not be fixed. Set the `NSSupportsAutomaticGraphicsSwitching=true` does not work for this case. This issue could be fixed automatically in the future if openjfx or later Java releases set default GPU behaviour as I have planted proper settings.
