### ISSUE TITLE
字符乱码/截图获取不稳定

### ISSUE THREAD

**Issue by qnxbwlyj** [blaisewang/img2latex-mathpix#23]
最新的Image2Latex 0.2.2-windows.zip文件中，双击bin文件夹中的Image2LaTeX.bat出现乱码情况。
运行环境：Windows10 1909 18363.535，没有安装任何Java或者Python等工作环境

### 1. 乱码情况说明：
所有字符均乱码，不论数字还是英文字母。包括输入的秘钥，软件可以工作
_1.1填写秘钥界面_
![image](https://user-images.githubusercontent.com/38348181/70766594-31bea180-1d99-11ea-94f7-875b4dfeda15.png)
_1.2软件主体界面_
![image](https://user-images.githubusercontent.com/38348181/70766611-3d11cd00-1d99-11ea-9665-75cacda3c397.png)

### 2.截图情况说明
我使用snipaste截图，然后复制，软件无法自动获取我所截的图，但是用搜狗输入法的截屏和天若文字识别的截图，软件可以自动获取截图并识别。识别出的字符乱码，但是复制粘贴后有效
_2.1无法获取snipaste截图_
![image](https://user-images.githubusercontent.com/38348181/70766929-56674900-1d9a-11ea-9b30-d13ef3ec5fde.png)
_2.2可以获取其他软件截图，但字符乱码_
![image](https://user-images.githubusercontent.com/38348181/70767004-98908a80-1d9a-11ea-87bb-a7b4afe8bc77.png)
_2.3识别出的公式有效_
![image](https://user-images.githubusercontent.com/38348181/70767053-bcec6700-1d9a-11ea-9b27-56bc92eaaf1d.png)

**Comment by blaisewang** [comment]
乱码问题应该是Windows的语言编码问题，你查看一下是不是修改过系统语言编码，比如GB2313，UTF-8等。

应用只会读取系统剪贴板判断是否有图片被截取，如果不能识别那说明使用的截图软件存放截图的位置可能不是在系统剪贴板中或者截图不是通用格式

**Comment by qnxbwlyj** [comment]
最近没有修改过系统语言编码，只不过昨天安装了搜狗输入法重启了电脑，不知道应该用哪一种系统语言编码？
snipsate截图在剪贴板中，上面的ditto剪贴板管理程序中显示有截图

**Comment by blaisewang** [comment]
> 最近没有修改过系统语言编码，只不过昨天安装了搜狗输入法重启了电脑，不知道应该用哪一种系统语言编码？
> snipsate截图在剪贴板中，上面的ditto剪贴板管理程序中显示有截图

理论上默认语言编码应该都没问题，毕竟所有字符串都是英文的，我只见过中文操作系统玩日文游戏乱码的。截图的话我不用Windows也没有办法对某个截图软件进行优化。

**Comment by qnxbwlyj** [comment]
非常感谢您和您的软件！！！
