### ISSUE TITLE
Windows隐藏cmd黑窗的建议

### ISSUE THREAD

**Issue by gongyan200** [blaisewang/img2latex-mathpix#24]
谢谢作者，你的软件很赞！
我有一个改善Windows平台软件使用体验的建议：
建议在Image2LaTeX.bat脚本的位置创建一个Image2LaTeX.vbs的脚本，内容为
```
set ws=WScript.CreateObject("WScript.Shell")
ws.Run "Image2LaTeX.bat",hide
```
cmd黑窗就可以被隐藏在后台，不显示在屏幕上了
希望考虑一下

**Comment by blaisewang** [comment]
感谢！非常好的想法！下个release会发布

**Comment by blaisewang** [comment]
@all-contributors please add @gongyan200 for ideas and tutorial
