### ISSUE TITLE
Broken Internet Connection Error

### ISSUE THREAD

**Issue by ldhpm2** [blaisewang/img2latex-mathpix#26]
Broken internet connection

**Comment by ldhpm2** [comment]
Broken internet connection

**Comment by blaisewang** [comment]
This error type indicates that there may be some issues with your internet.  More information is required to solve this problem. For example, can you access to [this website](https://api.mathpix.com/v3/latex).

**Comment by ldhpm2** [comment]
I used the Mathpix Snipping Tool to convert the photo-formula to mathtype
well, but Image2LaTeX-windows did not work, even though I signed in to APP
ID and APP Key.

>

**Comment by ldhpm2** [comment]
I used the Mathpix Snipping Tool to convert the photo-formula to mathtype well, but Image2LaTeX-windows did not work, even though I signed in to APP ID and APP Key.

**Comment by wtbsw** [comment]
The same problem occurs in my Macbook. Version 0.2.0 and 0.2.4 both have the problem. My system is Mojave. Could you please help me with that? Thank you very much!
THis is the logs.
![image](https://user-images.githubusercontent.com/14332504/71321214-61844c80-24f1-11ea-9953-98ecf6acfab9.png)

I can visit https://api.mathpix.com/ and the response is Mathpix server running!
But when I visit https://api.mathpix.com/v3/latex, the response is {"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}.

**Comment by blaisewang** [comment]
> But when I visit https://api.mathpix.com/v3/latex, the response is {"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}.

That's normal, don't worry about this.

To fix this, leave your email address here or send me an email (blaisewang(at)icloud.com) as I need to send you a debug version software.

**Comment by wtbsw** [comment]
I have sent you an email. If you have time, please send me the debug version of img2latex-mathpix. Thank you very much. @blaisewang

**Comment by blaisewang** [comment]
@all-contributors please add @wtbsw for bug, test
