### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ldhpm2** [blaisewang/img2latex-mathpix#29]
Version 0.26 works fine. I have a small suggestion:
Software should remove the Submit button, make it automatically switch back to Latex.

**Comment by blaisewang** [comment]
No need to start a separate issue for feedback. 

Sumbit button cannot be removed unless applying shortcuts. Every screenshot taken will be sent to the Mathpix server which will waste a lot of API usage.

**Comment by ldhpm2** [comment]
Remove the Sumbit button but add a screenshot function from the software,
making it similar to mathpix very convenient. Thanks.

>
