### ISSUE TITLE
[Feature Request] 增加运行中的加载界面

### ISSUE THREAD

**Issue by Xyzhao1999** [blaisewang/img2latex-mathpix#31]
**Is your feature request related to a problem? Please describe.**

0.2.7版中取消了Submit按钮用回车取代了，但是有时候因为网络或其他原因加载不出（我不确定是因为网络较慢还是没有触发）。

**Describe the solution you'd like**

希望可以增加loading界面或其他可以帮助判断是否在运行的功能。

**Comment by blaisewang** [comment]
是的，这个问题我也想过，但是loading过程只是等待服务器响应的过程，其他过程的时间可以忽略不计。下个版本可以尝试在界面添加一个指示物，用来告诉用户正在等待响应。

**Comment by Xyzhao1999** [comment]
是的，主要是觉得还是需要有提示，今天使用0.2.7的时候等待了很久一直没出来，后来才反应到时没有开始运行。

**Comment by blaisewang** [comment]
发布了 [v0.3.0](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.3.0) 版本
