### ISSUE TITLE
“Image2LaTeX-2.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by hamkz** [blaisewang/img2latex-mathpix#35]
System: MacOS 10.15.2
App version: 0.3.2
<img width="425" alt="Screen Shot 2019-12-30 at 4 21 59 AM" src="https://user-images.githubusercontent.com/12728942/71579963-ff60b400-2abb-11ea-8e6a-69c3a18df049.png">

**Comment by blaisewang** [comment]
Try: [1](https://github.com/hashicorp/terraform/issues/23033#issuecomment-539736692) or [2](https://github.com/hashicorp/terraform/issues/23033#issuecomment-540262070).

**Comment by acelik** [comment]
Can someone explain me how to get this to work? I cannot find "Image2LaTeX.app" file in the directory I downloaded. Readme is not clear enough to install this on mac OS machine.

**Comment by blaisewang** [comment]
> Can someone explain me how to get this to work? I cannot find "Image2LaTeX.app" file in the directory I downloaded. Readme is not clear enough to install this on mac OS machine.

You can find the latest macOS app `Image2LaTeX-0.7.5-macos.zip` at https://github.com/blaisewang/img2latex-mathpix/releases

**Comment by acelik** [comment]
Thank you sir for your prompt reply! After taking screenshot nothing happens, although I enter my API credentials.

**Comment by acelik** [comment]
> Thank you sir for your prompt reply! After taking screenshot nothing happens, although I enter my API credentials.

Anyway, I fixed it :)
