### ISSUE TITLE
[Bug] 网络不稳定

### ISSUE THREAD

**Issue by messier202** [blaisewang/img2latex-mathpix#36]
![image](https://user-images.githubusercontent.com/30891465/71653862-99995400-2d69-11ea-8fb8-5fa7e2de6d9d.png)
按下enter后一直处于Waiting状态(挂了梯子也是一样)，偶尔正常。app version：0.3.2，系统：mac osx 10.14.5 ，ubuntu 16.04。

**Comment by blaisewang** [comment]
这种描述问题的方式很难解决问题，如果不报错无法定位问题在哪。一直等待的话和你所在的省份，使用的ISP，代理服务器网络，代理方式都有关系。另外这应用默认不走代理，mac下强制走代理可以使用[Proxifier](http://proxifier.com/)试一下。

**Comment by blaisewang** [comment]
虽然我没办法确定无法获得结果是不是你网络的问题，但是一直waiting的确是之前存在的bug。这个bug已经在 [v0.3.3](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.3.3) 中修复了。
