### ISSUE TITLE
实现缩放

### ISSUE THREAD

**Issue by GongSiqiu** [blaisewang/img2latex-mathpix#42]
**Is your feature request related to a problem? Please describe.**
软件字体较小，名义上可以缩放，但内容并不随之改变
**Describe the solution you'd like**
真正实现缩放窗口

**Additional context**
![图片](https://user-images.githubusercontent.com/40697840/71974581-cb6c5800-324c-11ea-8710-89959204dfec.png)

**Comment by blaisewang** [comment]
这是Linux？

**Comment by GongSiqiu** [comment]
是的
debian 10

**Comment by blaisewang** [comment]
首先，缩放窗口这个操作并非是预期的行为，参考[这行代码](https://github.com/blaisewang/img2latex-mathpix/blob/master/src/main/java/MainAPP.java#L187)已经设置了应用窗口不可改变大小，这一属性在macOS, Windows和Ubuntu下工作正常，所以基本可以确定是你使用的Linux GUI shell的问题，而非代码问题。

其次，这个软件没有支持缩放的计划。简单的缩放窗口并不能增大字体，而增大字体要考虑应用的重新排版，这类的商业软件也很少支持调整界面上的字体大小。

**Comment by GongSiqiu** [comment]
不知道为什么现在已经不能缩放了

**Comment by blaisewang** [comment]
> 不知道为什么现在已经不能缩放了

不能缩放是正常的行为，不用担心
