### ISSUE TITLE
dash窗口并不能切换

### ISSUE THREAD

**Issue by GongSiqiu** [blaisewang/img2latex-mathpix#43]
**Describe the bug**
dash上显示有该程序，但点击并不能切换到该界面。只能通过小图标切换

**To Reproduce**
1. 打开程序
2. 点击图标

**Expected behavior**
切换到程序界面

**Screenshots**
![图片](https://user-images.githubusercontent.com/40697840/71974945-ccea5000-324d-11ea-871d-3381fd4ee655.png)
点不开
**Desktop (please complete the following information):**
 - OS: debian
 - Version 10

**Additional context**
其实如果能去掉这个图标也舒服一些

**Comment by blaisewang** [comment]
正如在 #42 中提到的，经过Ubuntu默认环境的测试，通过图标切换窗口的功能是正常的，窗口大小也是不可改变的。Linux有许多GUI shell，我也没有没有精力为每一个做优化，只能猜测是你使用的GUI shell对某些属性支持不完整。

**Comment by GongSiqiu** [comment]
是dash to panel插件的问题
