### ISSUE TITLE
[Bug]产生了大量的临时文件

### ISSUE THREAD

**Issue by YuiTH** [blaisewang/img2latex-mathpix#49]
**Describe the bug**
使用的是0.3.3版本，1月7日下载，在两天的使用中产生了大约260G的临时文件，产生路径为：C:\Users\{USER NAME}\AppData\Local\Temp
文件名字格式为~DFXXXXXXXXXX.TMP，二进制文件，大小从16K到16M不等。
产生了大约15w个临时文件。
**To Reproduce**
复现步骤不明，启动后使用一段时间挂在后台会自然产生，产生文件有周期性，一段时间内会持续产生大量文件后停止，过不定的时间继续产生。正常退出后停止产生文件，临时文件不会自动删除。

**Screenshots**
![image](https://user-images.githubusercontent.com/22416062/72159568-9c461a00-33f7-11ea-9795-3f12406a4012.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809

**Additional context**
并没有绝对的确认临时文件是因为本软件产生的，但是在产生临时文件的过程中（本软件在托盘运行）从托盘退出本软件，临时文件的生辰即刻停止，另外最早的该格式临时文件产生的日期是1月7日，与我下载本软件的时间一致，故推测。

**Comment by blaisewang** [comment]
我会尝试在虚拟机中确认一下这个问题是否存在

**Comment by blaisewang** [comment]
> 我会尝试在虚拟机中确认一下这个问题是否存在

已经确认问题存在了，而且很严重，建议在下个版本修复之前不要使用Windows版的，这个问题在macOS和Linux上都不存在。

**Comment by YuiTH** [comment]
明白，辛苦你深夜确认。除了我图上的路径，还会生成别的路径下的不会自动清理的临时文件吗？

**Comment by blaisewang** [comment]
> 明白，辛苦你深夜确认。除了我图上的路径，还会生成别的路径下的不会自动清理的临时文件吗？

应该是不会了。这个问题是因为程序开了一个线程去更新剪贴板中的截图，Windows下的线程可能会把剪贴板的图片保存成临时文件？如果没有合适的解决方法，那我就只能把Windows下的截图更新变成手动操作的了。

**Comment by YuiTH** [comment]
有没有可能跟Windows自带的那个剪贴板存储器（win+V）有关系？

**Comment by blaisewang** [comment]
应该是没有关系的，问题已经定位了，但是不太好解决。从一开始的设计思路上就过于注重实时显示截图而忽略了性能，可能要要改成点一下再显示截图了。

**Comment by YuiTH** [comment]
直接显示这个是很方便，不过也确实有点问题是真的，有时候截图什么奇怪的东西都会被塞进去预览感觉怪怪的。总之辛苦了。

**Comment by blaisewang** [comment]
@all-contributors please add @YuiTH for bug reports
