### ISSUE TITLE
打开应用，一次只能识别一个公式。再一次识公式，需要关闭再重新打开。

### ISSUE THREAD

**Issue by yeyeliu** [blaisewang/img2latex-mathpix#52]
**Describe the bug**
打开应用，一次只能识别一个公式。再一次识公式，需要关闭再重新打开。

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [Image2LaTeX-0.4.0-windows]

**Additional context**
谢谢

**Comment by blaisewang** [comment]
感谢报告，[v0.4.1](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.4.1)解决了这个问题
