### ISSUE TITLE
[Question] MAC 截图后clipboard image无显示

### ISSUE THREAD

**Issue by XinDongol** [blaisewang/img2latex-mathpix#59]
如题

**Comment by XinDongol** [comment]
version 0.4.3

**Comment by blaisewang** [comment]
从v0.4.0开始，截图之后需要使用空格键预览截图，回车键发送请求。

[v0.4.0更新记录](https://github.com/blaisewang/img2latex-mathpix/releases)

**Comment by XinDongol** [comment]
可以了，谢谢。
