### ISSUE TITLE
[Feature] not removing linebreaks

### ISSUE THREAD

**Issue by JakeWrights** [blaisewang/img2latex-mathpix#60]
One difference I noticed between the actual mathpix app and this version is that there is no word wrap. For some reason there will be new lines inserted in places while the mathpix by default will remove those linebreaks.

**Comment by blaisewang** [comment]
I don't recall any post-processing on the OCR results. It would be great if you could provide an example equation to illustrate the problem.

**Comment by JakeWrights** [comment]
Hi, yes here's an example 
You can see how the mathpix app will remove the linebreaks. 
![origin_image](https://user-images.githubusercontent.com/19579506/74081484-5b482200-4a04-11ea-80dd-dd47114c7942.png)

[ex.txt](https://github.com/blaisewang/img2latex-mathpix/files/4173901/ex.txt)

**Comment by JakeWrights** [comment]
Oh actually I figured out why- it seems to be the difference between v1 and v2 OCR version in mathpix snip. Is v2 not offered  in the mathpix OCR?

**Comment by blaisewang** [comment]
I am guessing that you are using OCR Version 2.0 in the mathpix snip. You can confirm it by finding the OCR version option in `Preferences` - `General`.  The result from Image2LaTeX is as the same as mathpix snip with OCR version 1.0. However, I could remove linebreaks as the request parameters can be customised. Technically, it's not a bug, so I will use an enhancement label to replace it. Will add this in next release. But, I am quite busy recently, not sure when I will release a new version.

**Comment by blaisewang** [comment]
I have been working on the new version for a couple of hours. I have tried adding the `rm_newlines` parameter to remove line breaks. However, the obtained result is different from OCR Version 2.0 in the Mathpix snip.

```
Confidence Interval. Let \(X_{1}, X_{2}, \ldots, X_{n}\) be a sample on a random variable \(X,\) where \(X\) has pdf \(f(x | \theta) .\) Let \(0<\alpha<1\) be specified. Let \(L=L\left(X_{1}, \ldots, X_{n}\right)\) and \(U=U\left(X_{1}, \ldots, X_{n}\right)\) be two statistics. We say that the interval \((L, U)\) is a \((1-\alpha) 100 \%\) confidence interval for \(\theta\) if
\[ 1-\alpha=P_{\theta}[(L, U) \ni \theta] \] The probability that the random interval \((L, U)\) includes \(\theta\) is \(1-\alpha,\) also called confidence level of the interval.
```

As you can see, the `rm_newlines` parameter will cause line breaks between the end of the paragraph and latex to be removed. I don't think this is a viable result, so I will not keep this option in the preferences.

If mathpix made their OCR Version 2.0 API available in the future, I will add this option to the preferences.
