### ISSUE TITLE
[Feature Request] 是否可以考虑增加LaTeX转MathML功能

### ISSUE THREAD

**Issue by Xyzhao1999** [blaisewang/img2latex-mathpix#62]
**Is your feature request related to a problem? Please describe.**

该想法来源近期写论文贴公式的流程。由于学校要求只能用Word，虽然Word现在支持使用LaTeX作为公式源，但部分公式仍显示不正常。且根据某些资料（不一定可靠）LaTeX公式在查重中可能有问题。
目前的方法是MathpixOCR转图片为LaTeX，然后LaTeX转MathML，最后增加对应xml标签粘贴到Word。具体流程可见[https://www.pzhao.org/zh/post/latex-equations-to-word/](https://www.pzhao.org/zh/post/latex-equations-to-word/)
该方法有效但步骤略繁琐，故想增加该功能。

**Describe the solution you'd like**

该方法我在0.3.0版本上有魔改实现过，LaTeX转MathML使用的是snuggletex。（但近期想在新版本上进行修改时idea编译运行出错，似乎总是提示javafx有问题，还没有找到原因...所以搁浅了）

**Describe alternatives you've considered**

在主页中增加该功能区或在设置中进行开关。
由于该功能可能不是普遍需求，我可以尽可能提供一些帮助。

**Comment by blaisewang** [comment]
[Mathpix OCR API](https://docs.mathpix.com/#formatting8) 是支持直接输出 MathML 结果的，你可以 clone 这个项目，替换 [Recognition.java](https://github.com/blaisewang/img2latex-mathpix/blob/master/src/main/java/io/Recognition.java) 75或者76行为 `"mathml"`，编译自己的版本。

写论文主要还是latex，所以感觉大部分人不太需要mathml，你可以先自己修改一下。

**Comment by Xyzhao1999** [comment]
多谢提醒！我会再看一看的！

**Comment by Xyzhao1999** [comment]
感谢提供的帮助，目前已经改出来了。官方API提供的mathml格式在Word中似乎不太适用，最后还是使用了对应库转的。还是谢谢你的帮助。。

**Comment by Lyndon-wong** [comment]
> 感谢提供的帮助，目前已经改出来了。官方API提供的mathml格式在Word中似乎不太适用，最后还是使用了对应库转的。还是谢谢你的帮助。。

您好！我最近也遇到了同样的问题：我发现官方输出的mathml格式第一行必须修改才能被word识别，请问您是怎么解决这个问题的？调用了什么对应库？

**Comment by Xyzhao1999** [comment]
> > 感谢提供的帮助，目前已经改出来了。官方API提供的mathml格式在Word中似乎不太适用，最后还是使用了对应库转的。还是谢谢你的帮助。。
> 
> 您好！我最近也遇到了同样的问题：我发现官方输出的mathml格式第一行必须修改才能被word识别，请问您是怎么解决这个问题的？调用了什么对应库？

@Lyndon-wong 使用的是snuggletex库，我修改的版本已经传到我的github上了  不过我没有对其进行打包，需要您自行打包。
