### ISSUE TITLE
[Bug]Win10运行vbs文件报错：系统找不到"系统找不到指定的文件"

### ISSUE THREAD

**Issue by cauchy7203** [blaisewang/img2latex-mathpix#63]
![image](https://user-images.githubusercontent.com/9944333/76625816-00f63000-6573-11ea-8150-968e9bed602f.png)

**Comment by cauchy7203** [comment]
OK,THANKS.

我在想可能就是路径的问题。

**Comment by blaisewang** [comment]
The new Windows version with executable `exe` should fix this.

https://github.com/blaisewang/img2latex-mathpix/releases
