### ISSUE TITLE
0.6.0 mac 软件没有反应

### ISSUE THREAD

**Issue by water-wbq** [blaisewang/img2latex-mathpix#65]
你好，我下载了0.6.0 mac版本，使用系统自带的戳图工具后，软件没有反应。
我已经做的操作：开启了系统偏好设置中的输入监视，设置了api id。不知道是不是我还有操作没有做好，希望能得到指点，谢谢。

**Comment by water-wbq** [comment]
戳图戳好后，按空格没用，按回车有效。
对不起，打扰了~

**Comment by blaisewang** [comment]
> 戳图戳好后，按空格没用，按回车有效。
> 对不起，打扰了~

空格也应该是ok的啊，你按空格的时候app应该是激活的状态

**Comment by chenkaiwenguo** [comment]
您好，我下载了0.7.5Windows版本，在这一步通不过![NLX CQBT$YJ@6I%9 H2DC3I](https://user-images.githubusercontent.com/64178777/80295241-c0a9e480-87a3-11ea-93bf-b1c72e3f2e69.png)
无法设置api id.不知道是不是已经申请不了了还是我的问题，希望能得到指点，谢谢.
