### ISSUE TITLE
[Feature Request]How to reduce a $ sign?

### ISSUE THREAD

**Issue by zscaorui** [blaisewang/img2latex-mathpix#70]
![image](https://user-images.githubusercontent.com/38314909/78119964-c974f800-743b-11ea-8c60-fb8b0ae5b262.png)
The result is now 【$$
   \ mathrm {Cl} ^ {-} \ left (0.1 \ mathrm {mol} \ cdot \ mathrm {kg} ^ {-1} \ right) = 1/2 \ mathrm {Cl} _ {2} \ left (\ mathrm {g}, p ^ {\ ominus} \ right) + \ mathrm {e} ^ {-}
$$】，how can I change to 【$
   \ mathrm {Cl} ^ {-} \ left (0.1 \ mathrm {mol} \ cdot \ mathrm {kg} ^ {-1} \ right) = 1/2 \ mathrm {Cl} _ {2} \ left (\ mathrm {g}, p ^ {\ ominus} \ right) + \ mathrm {e} ^ {-}
$】，only  reduce a $ sign？

**Comment by blaisewang** [comment]
Not support yet. Will consider to implement it in the future
