### ISSUE TITLE
[Bug] data is sent multiple times

### ISSUE THREAD

**Issue by hmf** [blaisewang/img2latex-mathpix#76]
**Describe the bug**
I used the MathPix dashboard to check on my information and observed more recorded requests than I had done. 

**To Reproduce**
1. Launched the application
2. Took a screen shot
3. Used return to send the request
4. Received response
5. Went to the dashboard and observed an extra request

**Expected behavior**
I expected one message per button press. 

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 
 - Version 18.04

**Additional context**
I changed the code and added `println` to confirm what was happening. 
The message was in fact sent twice. I then confirmed that no press de-bounce
code was present in the Java code.  

I have added de-bounce to the  `BackGridPane`class [here](https://github.com/hmf/img2latex-mathpix/blob/jdk11/src/main/java/ui/BackGridPane.java#L148).

I also added additional changes to the accepted keys:
* `insert` to do the same as `backspace`
* `delete` to do the same as `enter`

The reason is that the `enter` will only work if one of the text fields have focus. 
However the `delete` is always detected (like the backspace) and allows us
to forego the selection of a text field. 

If you like, I can make a pull request with these changes.

**Comment by blaisewang** [comment]
Hi, the data was sent to two APIs for different purposes. [v3/text API](https://docs.mathpix.com/#process-image-v3-text) was queried for advanced features, such as paragraph OCR, basic table OCR, MathML result, TSV result, and more. [v3/latex](https://docs.mathpix.com/#legacy-endpoint-v3-latex) was queried for rendering the results. Sending two requests was introduced in [v0.6.0](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.6.0). 

In the second latest version [v0.7.3](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.7.3), the legacy v3/latex API was removed. The cost of removing this API is the user cannot view some rendered result (only equations will be rendered), they need to paste the result into a LaTeX editor before they can view the results.

With removing the legacy API, each data will be sent once now.

I got a few issue reports about the key listening problem. I cannot explain why but indeed sometimes the key listening just doesn't work no matter which key you chose. In fact, the reason why I chose Backspace for preview is I got a report saying that the Space key doesn't work. You may try the latest version in this repo (v0.7.4) to see if it's working or not.

**Comment by blaisewang** [comment]
In theory, all key listening should work. If you wish, you may try to figure out why sometimes some key just doesn't work. Eventually, I would still like to use the Space key for preview screenshot and the Enter key for making OCR requests.

**Comment by hmf** [comment]
If I understand correctly the latest `master` version is not using the legacy [v3/latex API](https://docs.mathpix.com/#process-image-v3-text). If so then only one request is made. I think I am using the latest `master`. However, note that I debugged the system, so I am pretty sure several key strokes are processed sequentially. It is the same issue you dealt with in the case o the backspace - only their you use a timer.

**Comment by hmf** [comment]
Some keys are only processed by some JavaFX nodes. The top tier nodes don't. Text fields do.  Maybe the issue with space is the same. Try and set focus on one of the text fields and then press space. Maybe setting the focus automatically will solve your problem. HTH.

**Comment by blaisewang** [comment]
Good thought.
