### ISSUE TITLE
建议增加“显示使用次数”的功能

### ISSUE THREAD

**Issue by tzqp** [blaisewang/img2latex-mathpix#78]
建议增加“显示使用次数”的功能，这样每个月就可以比较清楚自己大概使用了多少次，做到心中有数

**Comment by blaisewang** [comment]
没有这个api，没办法做这个功能，只有软件计数是不准的

**Comment by tzqp** [comment]
对单个用户而言，这项功能依然是有意义的

**Comment by tzqp** [comment]
就像安卓手机普遍存在的流量统计功能，实际会和运营商的统计有差异，但依然可以给用户作为参考。
