### ISSUE TITLE
[Question] Where to download

### ISSUE THREAD

**Issue by acelik** [blaisewang/img2latex-mathpix#79]
Can someone explain me how to get this app to work on Mac OS environment? I am unable to locate executable files in the dowloaded directory.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 0.2.1]

**Additional context**

**Comment by blaisewang** [comment]
https://github.com/blaisewang/img2latex-mathpix/releases
