### ISSUE TITLE
on Config File Creation

### ISSUE THREAD

**Issue by NYXFLOWER** [blaisewang/img2latex-mathpix#8]
Could you please so kind to put an example or some descriptions on how to create a config file, or what a config file it should look like?

**Comment by blaisewang** [comment]
You will get a `config` file when you run this app for the first time. Replace the value after `=` with real API Keys. You will get your API Keys at [Mathpix dashboard](https://dashboard.mathpix.com/).

**Comment by NYXFLOWER** [comment]
Thank you for your explanation. 

It's maybe more clear if you could put the config setting guidance behind the app download part in the Usage section, such that the users can set the app up step by step.

**Comment by blaisewang** [comment]
I have added a new API key setting panel. See release [v0.2.0](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.2.0).

![Settings](https://user-images.githubusercontent.com/9657268/68365010-82275b80-016a-11ea-9cd7-5511ba44cf8c.png)

**Comment by blaisewang** [comment]
@all-contributors please add @NYXFLOWER for Ideas
