### ISSUE TITLE
[Bug] Cost too much power in macos

### ISSUE THREAD

**Issue by iuk** [blaisewang/img2latex-mathpix#80]
It seems that image2latex cost too much power in macos

![image](https://user-images.githubusercontent.com/2498767/81033652-f4cd8580-8ec6-11ea-8943-6d78a26ab12b.png)

**Comment by iuk** [comment]
原来作者是国人呀，厉害，我是发现这个程序好像比较耗电，在笔记本使用电池时会比较担心。

在活动监视器里是这个样子的：
![image](https://user-images.githubusercontent.com/2498767/81033977-2135d180-8ec8-11ea-9cbe-797171544f59.png)

**Comment by blaisewang** [comment]
Duplicate of #22

**Comment by blaisewang** [comment]
目前看来 javafx 默认会用独立显卡，这会导致功耗上升，我也不太清楚怎么解决这一个问题。

**Comment by iuk** [comment]
确实是java的问题，我电脑上另一个使用java的软件 yed 也会主动使用独立显卡。
我现在使用 gfxcardstatus 禁用独立显卡，可以避免这个问题。
