### ISSUE TITLE
Windows系统0.7.5识别提示错误

### ISSUE THREAD

**Issue by chenkaiwenguo** [blaisewang/img2latex-mathpix#81]
![image](https://user-images.githubusercontent.com/64178777/81759693-fb2bb500-94f7-11ea-8fc4-ee576e5d42d8.png)

**Comment by blaisewang** [comment]
这个报错的意思是网络问题，是每次都会遇到吗？还是偶发？

**Comment by chenkaiwenguo** [comment]
是每次，而且我用了二台电脑试了，其中一台是全新电脑，都出现同样的情况


---原始邮件---
发件人: &quot;Blaise Wang&quot;<notifications@github.com&gt;
发送时间: 2020年5月13日(周三) 中午12:23
收件人: &quot;blaisewang/img2latex-mathpix&quot;<img2latex-mathpix@noreply.github.com&gt;;
抄送: &quot;chenkaiwenguo&quot;<1197345832@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [blaisewang/img2latex-mathpix] Windows系统0.7.5识别提示错误 (#81)




 
这个报错的意思是网络问题，是每次都会遇到吗？还是偶发？
 
&mdash;

**Comment by blaisewang** [comment]
有开启 http prxoy 吗？

**Comment by chenkaiwenguo** [comment]
开启的



---原始邮件---
发件人: "Blaise Wang"<notifications@github.com&gt;
发送时间: 2020年5月13日(周三) 下午3:05
收件人: "blaisewang/img2latex-mathpix"<img2latex-mathpix@noreply.github.com&gt;;
抄送: "chenkaiwenguo"<1197345832@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [blaisewang/img2latex-mathpix] Windows系统0.7.5识别提示错误 (#81)




 
有开启 http prxoy 吗？

**Comment by blaisewang** [comment]
尝试关掉 http proxy 选项用下

**Comment by chenkaiwenguo** [comment]
出现另一种提示


---原始邮件---
发件人: "Blaise Wang"<notifications@github.com&gt;
发送时间: 2020年5月14日(周四) 上午10:37
收件人: "blaisewang/img2latex-mathpix"<img2latex-mathpix@noreply.github.com&gt;;
抄送: "chenkaiwenguo"<1197345832@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [blaisewang/img2latex-mathpix] Windows系统0.7.5识别提示错误 (#81)




 
尝试关掉 http proxy 选项用下

**Comment by ZQ227** [comment]
请问为什么macos系统下，一定要先点击软件使其正在使用，方可截图识别，如果我不点击软件，虽然说软件也会窗口置顶，但是此时截图后按下回车键并不会识别图像

**Comment by chenkaiwenguo** [comment]
不好意思，我用的是Windows系统，但至今还没能成功识别图像


---原始邮件---
发件人: &quot;ZQ227&quot;<notifications@github.com&gt;
发送时间: 2020年5月20日(周三) 下午3:12
收件人: &quot;blaisewang/img2latex-mathpix&quot;<img2latex-mathpix@noreply.github.com&gt;;
抄送: &quot;chenkaiwenguo&quot;<1197345832@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [blaisewang/img2latex-mathpix] Windows系统0.7.5识别提示错误 (#81)




 
请问为什么macos系统下，一定要先点击软件使其正在使用，方可截图识别，如果我不点击软件，虽然说软件也会窗口置顶，但是此时截图后按下回车键并不会识别图像
 
&mdash;

**Comment by ZQ227** [comment]
好的，谢谢

**Comment by blaisewang** [comment]
> 请问为什么macos系统下，一定要先点击软件使其正在使用，方可截图识别，如果我不点击软件，虽然说软件也会窗口置顶，但是此时截图后按下回车键并不会识别图像

因为java程序在非激活状态下不能监听按键事件

**Comment by ZQ227** [comment]
诶....那可有点麻烦了

**Comment by ZQ227** [comment]
不过免费软件还是很感激了

**Comment by chenkaiwenguo** [comment]
虽然Windows系统暂时用不了，还是觉得开发者像雷锋很大方，希望能继续更新解决现在的问题，期待早日用上


---原始邮件---
发件人: &quot;Blaise Wang&quot;<notifications@github.com&gt;
发送时间: 2020年5月20日(周三) 下午3:32
收件人: &quot;blaisewang/img2latex-mathpix&quot;<img2latex-mathpix@noreply.github.com&gt;;
抄送: &quot;chenkaiwenguo&quot;<1197345832@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [blaisewang/img2latex-mathpix] Windows系统0.7.5识别提示错误 (#81)




  
请问为什么macos系统下，一定要先点击软件使其正在使用，方可截图识别，如果我不点击软件，虽然说软件也会窗口置顶，但是此时截图后按下回车键并不会识别图像
  
因为java程序在非激活状态下不能监听按键事件
 
&mdash;

**Comment by blaisewang** [comment]
@chenkaiwenguo windows用户还挺多的，麻烦确认一下关掉 http proxy 选项之后的错误是什么？

**Comment by chenkaiwenguo** [comment]
您好，提示这个，是不是我的API不行


---原始邮件---
发件人: "Blaise Wang"<notifications@github.com&gt;
发送时间: 2020年5月22日(周五) 下午5:22
收件人: "blaisewang/img2latex-mathpix"<img2latex-mathpix@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"chenkaiwenguo"<1197345832@qq.com&gt;;
主题: Re: [blaisewang/img2latex-mathpix] Windows系统0.7.5识别提示错误 (#81)




 
@chenkaiwenguo windows用户还挺多的，麻烦确认一下关掉 http proxy 选项之后的错误是什么？

**Comment by blaisewang** [comment]
没看到图，如果是 Invalid credentials 那就是账号密钥错误

**Comment by chenkaiwenguo** [comment]
账号秘钥按该链接(我用#CSDN#这个app发现了有技术含量的博客，小伙伴们求同去《Image2LaTeX&nbsp;+&nbsp;AxMath：公式自动识别&nbsp;+&nbsp;word&nbsp;编辑公式》,&nbsp;一起来围观吧&nbsp;https://blog.csdn.net/Miss_leaf/article/details/103940635?utm_source=app)中的操作，申请不了。问题出现在最后一步，接受点击没有反应，后面我安装更新了的，就自动有了。

请问这个问题改怎么解决，谢谢


---原始邮件---
发件人: "Blaise Wang"<notifications@github.com&gt;
发送时间: 2020年5月22日(周五) 晚上10:16
收件人: "blaisewang/img2latex-mathpix"<img2latex-mathpix@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"chenkaiwenguo"<1197345832@qq.com&gt;;
主题: Re: [blaisewang/img2latex-mathpix] Windows系统0.7.5识别提示错误 (#81)




 
没看到图，如果是 Invalid credentials 那就是账号密钥错误

**Comment by blaisewang** [comment]
当然是不要使用别人的 api 密钥

**Comment by chenkaiwenguo** [comment]
API申请不了，有什么办法解决吗？


---原始邮件---
发件人: &quot;Blaise Wang&quot;<notifications@github.com&gt;
发送时间: 2020年5月25日(周一) 中午12:38
收件人: &quot;blaisewang/img2latex-mathpix&quot;<img2latex-mathpix@noreply.github.com&gt;;
抄送: &quot;Mention&quot;<mention@noreply.github.com&gt;;&quot;chenkaiwenguo&quot;<1197345832@qq.com&gt;;
主题: Re: [blaisewang/img2latex-mathpix] Windows系统0.7.5识别提示错误 (#81)




 
当然是不要使用别人的 api 密钥
 
&mdash;
