### ISSUE TITLE
每次截图之后，只能使用一次，再次截图摁Enter键软件无反应。

### ISSUE THREAD

**Issue by guandd** [blaisewang/img2latex-mathpix#83]
**Describe the bug**
win10 64位系统，下载的使用0.7.5版本。
打开软件后第一次操作：使用快捷键微信Alt+A截图之后，单击软件，然后摁Enter键，可以使用。
第二次进行同样的操作，截图，单击软件，摁Enter键**软件无反应**，退出软件重新打开，ClipBoard Image区域直接显示关闭之前截图的公式。

核心问题就是：在我电脑上，软件只能用一次，就没反应了，关闭重新打开软件还是只能用一次。。。重启电脑、更换截图软件还是一样的问题。

**Comment by blaisewang** [comment]
我在 Windows 10 也试了一下，没有复现你的问题，不过我知道这确实是一个反复出现的 bug。在第一次识别之后，做了哪些操作？第二次识别前按空格可以预览截图吗？

**Comment by blaisewang** [comment]
第二次识别前可以把结果粘贴到聊天框里吗？

**Comment by guandd** [comment]
> 我在 Windows 10 也试了一下，没有复现你的问题，不过我知道这确实是一个反复出现的 bug。在第一次识别之后，做了哪些操作？第二次识别前按空格可以预览截图吗？

1. 第一次我识别之后，复制latex代码，然后打开Mathtype，把代码复制到了Mathtype中（主要用于生成ppt中的公式）。完成之后再Alt+A截图下一个公式，点击软件就没反应了。不知道是不是和使用Mathtype这个操作有关系？
2. 关闭之后第二次打开软件直接点击就可以预览截图了，不需要摁下空格键

**Comment by guandd** [comment]
> 第二次识别前可以把结果粘贴到聊天框里吗？

可以，我任何一次截图都可以粘贴到微信聊天框

**Comment by blaisewang** [comment]
不打开 mathtype 的情况下能两次截图识别吗？

**Comment by guandd** [comment]
> 不打开 mathtype 的情况下能两次截图识别吗？

我看了之前的issue，重新安装了0.4.1版本，第一天用正常，可以多次截图识别。现在（第二天）关闭mathtype，也只能识别一次了。不知道哪里出了问题？

**Comment by blaisewang** [comment]
这个bug确实比较神奇，有时间我会考虑加个button去彻底解决这个问题

**Comment by blaisewang** [comment]
已在 0.7.6 中加单独的提交按钮，

**Comment by Broduker** [comment]
我也经常出现这种现象，只有设置提交按钮是没问题的

**Comment by blaisewang** [comment]
这个应用优先级比较低，回车键有可能被其他应用注册掉了， 所以导致这个应用无法发送请求
