### ISSUE TITLE
[Bug] 识别时间过长，且经常time required out

### ISSUE THREAD

**Issue by Broduker** [blaisewang/img2latex-mathpix#85]
**Describe the bug**
每次截图后进行公式识别时，waiting时间过长，并偶尔出现time required out，确认本地网络没有问题。
不知道是调用api本身的问题，还是软件的bug。

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [10.0.18362]

**Comment by blaisewang** [comment]
time required out 一般是等待响应时间过长，目前是 15 秒拿不到返回值就会报错，如果有科学上网的工具可以配置一下设置里的 HTTP proxy

**Comment by Broduker** [comment]
好的 感谢

**Comment by cakexxx** [comment]
> time required out 一般是等待响应时间过长，目前是 15 秒拿不到返回值就会报错，如果有科学上网的工具可以配置一下设置里的 HTTP proxy

能否自定义网址，我选择软件指向一个镜像网站

**Comment by blaisewang** [comment]
> > time required out 一般是等待响应时间过长，目前是 15 秒拿不到返回值就会报错，如果有科学上网的工具可以配置一下设置里的 HTTP proxy
> 
> 能否自定义网址，我选择软件指向一个镜像网站

是指不用 Mathpix OCR API 服务器的地址吗？这个功能需求太小，估计不太可能实现，建议还是用 http proxy 或者自己编译一版，只需要改一下地址就好了。
