### ISSUE TITLE
Macbook截取屏幕上传后，要么显示HTTP connect time out,或者显示received close——notify during handshaking

### ISSUE THREAD

**Issue by edward9503** [blaisewang/img2latex-mathpix#88]
你好，一开始使用的时候都没有出现这些问题。第二第三次后就出现这些问题。图片能导入，但是不能生成latex代码。error如题。谢谢

**Comment by blaisewang** [comment]
请求超时了，线路不太好，如果有科学上网的工具可以配一下 http proxy

**Comment by edward9503** [comment]
谢谢回复，可是我人在国外，不应该会有这样的问题吧？

**Comment by blaisewang** [comment]
命令行执行 `for i in {1..20}; do time curl https://api.mathpix.com/v3/text ; done;`，看 total 时间有多少秒，另外截图分辨率是不是比较大？试下[这张图片](https://mathpix.com/images/ocr-page/formula_2@2x.jpg)

**Comment by edward9503** [comment]
你好，这是命令行输出的。还有试了您给的图片也不行
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.707s
user	0m0.028s
sys	0m0.024s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.293s
user	0m0.028s
sys	0m0.018s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.297s
user	0m0.031s
sys	0m0.018s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.284s
user	0m0.031s
sys	0m0.016s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.187s
user	0m0.029s
sys	0m0.020s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.179s
user	0m0.026s
sys	0m0.013s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.184s
user	0m0.026s
sys	0m0.016s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.179s
user	0m0.025s
sys	0m0.014s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.275s
user	0m0.027s
sys	0m0.016s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.194s
user	0m0.028s
sys	0m0.016s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.171s
user	0m0.025s
sys	0m0.014s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.178s
user	0m0.027s
sys	0m0.014s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.168s
user	0m0.027s
sys	0m0.012s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.177s
user	0m0.025s
sys	0m0.017s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.190s
user	0m0.027s
sys	0m0.019s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.289s
user	0m0.027s
sys	0m0.020s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.183s
user	0m0.027s
sys	0m0.016s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.177s
user	0m0.025s
sys	0m0.014s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.181s
user	0m0.027s
sys	0m0.016s
{"error":"Invalid credentials","error_info":{"id":"http_unauthorized","message":"Invalid credentials"}}
real	0m0.188s
user	0m0.031s
sys	0m0.016s

**Comment by blaisewang** [comment]
感觉和你的网络提供商没关系，周末我看一下

**Comment by edward9503** [comment]
好的非常感谢

**Comment by wtbsw** [comment]
您好，我也遇到了同样的问题。0.7.0、0.7.6版本有问题，0.5.0版本可以正常使用。

**Comment by edward9503** [comment]
> 您好，我也遇到了同样的问题。0.7.0、0.7.6版本有问题，0.5.0版本可以正常使用。

谢谢分享，的确，我也是用0.5.0就可以正常使用了

**Comment by edward9503** [comment]
> 感觉和你的网络提供商没关系，周末我看一下

您好，用0.5.0版本就没有问题了。供参考

**Comment by blaisewang** [comment]
> > 感觉和你的网络提供商没关系，周末我看一下
> 
> 您好，用0.5.0版本就没有问题了。供参考

感谢提供的参考，问题在 [v0.7.7](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.7.7) 中解决掉了

**Comment by edward9503** [comment]
> > > 感觉和你的网络提供商没关系，周末我看一下
> > 
> > 
> > 您好，用0.5.0版本就没有问题了。供参考
> 
> 感谢提供的参考，问题在 [v0.7.7](https://github.com/blaisewang/img2latex-mathpix/releases/tag/v0.7.7) 中解决掉了

非常感谢

**Comment by blaisewang** [comment]
> 您好，我也遇到了同样的问题。0.7.0、0.7.6版本有问题，0.5.0版本可以正常使用。

同样感谢提供的参考

**Comment by blaisewang** [comment]
@all-contributors please add @edward9503 @wtbsw for bug reports

**Comment by blaisewang** [comment]
@all-contributors please add @edward9503 for the bug report, add @wtbsw for the bug report.
