### ISSUE TITLE
总是出现connection reset

### ISSUE THREAD

**Issue by xiaoduoli** [blaisewang/img2latex-mathpix#92]
windows 10系统，总是出现connection reset，无法返回结果，等一段时间就好了，但很快就又会出现connection reset。

**Comment by xiaoduoli** [comment]
截图之后按回车，就出现connection reset，无法返回结果，等一段时间就好了，但很快就又会出现connection reset。

**Comment by blaisewang** [comment]
升级到最新版尝试配置一下 http proxy

**Comment by xiaoduoli** [comment]
已经是最新版了，http proxy怎么配置呢？

**Comment by blaisewang** [comment]
Preferences - HTTP Proxy
