### ISSUE TITLE
[建议] 窗口能像 mathpix 那样缩进 menu 图标吗？或者能被其他窗口挡住也行

### ISSUE THREAD

**Issue by yoyooyooo** [blaisewang/img2latex-mathpix#95]
现在无脑最前面很不好啊想隐藏都不行，这次关了等下再用又得再开

**Comment by blaisewang** [comment]
建议收到，下个版本考虑一下

**Comment by yoyooyooo** [comment]
> 建议收到，下个版本考虑一下

另外formatting 符号能不能加个选项，我希望代码部分用$...$包裹的时候左右不额外加空格，现在是多加了个空格：$ ... $
