### ISSUE TITLE
[Bug] Content not found

### ISSUE THREAD

**Issue by isping** [blaisewang/img2latex-mathpix#96]
**Describe the bug**
error msg: Content not found
it worked fine before today. I don't know what caused this matter.

**To Reproduce**
正常复制粘贴，手动submit，返回提示信息：Content not found.

**Expected behavior**
反回出错。以前一直正常。

**Screenshots**
![d](https://user-images.githubusercontent.com/4645233/95670595-00cd1a00-0bc0-11eb-935e-16949e17b015.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7]
 - Version [e.g. 0.7.7]

**Additional context**

**Comment by blaisewang** [comment]
Content not found 的报错是 mathpix 返回的，截取的图片确认不是空白的吗？或者分辨率太低？

**Comment by isping** [comment]
图片确认不是空白的，以前一直是这样用都是可以的，我用mathpix官方的软件，同样的截图没有问题，可以识别。

**Comment by blaisewang** [comment]
电脑中装有 Python 3 吗？麻烦先截图，然后运行以下代码，然后测试截图是否可以使用 app 进行 OCR。如果不行，麻烦上传以下 Python 代码运行之后生成的 debug.data 文件。代码运行需要安装 Pillow ，`python3 -m pip install Pillow`。

```
from PIL import ImageGrab

im = ImageGrab.grabclipboard()
with open("debug.data", "wb") as f:
    f.write(im.tobytes())
```

**Comment by isping** [comment]
[debug.zip](https://github.com/blaisewang/img2latex-mathpix/files/5374790/debug.zip)


![python3](https://user-images.githubusercontent.com/4645233/95928600-5be75280-0df4-11eb-85d1-d995532b95a4.png)
下面是使用官方app可以返回正常的公式
![无标题](https://user-images.githubusercontent.com/4645233/95928692-a072ee00-0df4-11eb-87f2-40d35050c4c6.png)

**Comment by blaisewang** [comment]
麻烦这次运行以下代码，并同样把 debug.data 上传上来。

```
from PIL import ImageGrab

im = ImageGrab.grabclipboard()
with open("debug.data", "wb") as f:
    f.write(im.tobytes())
print(im.size, im.mode)
```

**Comment by isping** [comment]
[debug.zip](https://github.com/blaisewang/img2latex-mathpix/files/5381776/debug.zip)
运行代码返回信息：
175974
(422, 139) RGB

**Comment by blaisewang** [comment]
试下这个版本，还会不会出现同样的问题 https://github.com/blaisewang/img2latex-mathpix/releases/download/v0.7.8-alpha/Image2LaTeX-0.7.8-windows.zip

**Comment by isping** [comment]
还是同样的错误
还有一个问题，就是我将图像复制到粘贴板的时候，Image2Latex软件Clipboard Image显示也是空白的，使用空格键提交不起作用，都要用submit提交。前段时间是好用，最近就不行了，不知道啥引起的。

**Comment by isping** [comment]
试了另外一些文档，有的是成功的。 可能原因是，有的文档截图后clipboard image区域里并没有显示，发送了空的数据到服务器？不过同样的文档，用mathipx就没问题，因为mathipx是有自己的截图工具。

**Comment by Broduker** [comment]
我最近也遇到了相同的问题 之前用还正常

**Comment by IsumiAlice** [comment]
今天剛開始使用，也遇到了類似的問題，個人發現和截圖程式有關，我用 Snipaste2.3.0 會出錯，但 Tim 自帶的截圖 ok

**Comment by blaisewang** [comment]
我尝试了数周，还是没办法复现这个问题，但是上面给出的 debug data 确实报相同的错误，目前没有进展

**Comment by chenkaiwenguo** [comment]
我期盼更新能解决这个问题，但是到目前还是不行，总是出现错误提示，请问是什么原因导致的，有什么办法可以解决吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blaisewang/img2latex-mathpix"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 晚上8:37
收件人:&nbsp;"blaisewang/img2latex-mathpix"<img2latex-mathpix@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [blaisewang/img2latex-mathpix] [Bug] Content not found (#96)





 
我尝试了数周，还是没办法复现这个问题，但是上面给出的 debug data 确实报相同的错误，目前没有进展

**Comment by wtbsw** [comment]
我也遇到了同样的问题，使用snipaste的截图无法识别，但是qq截图可以，我最后使用Lightshot，它的截图也能识别，感觉是snipaste 的问题。

**Comment by LCHSuper** [comment]
感觉应该是snipaste的问题，换个截图软件就任何问题都没有了，希望开发者可以做一下与snipaste截图的适配，感谢感谢！

**Comment by zhongfly** [comment]
在Snipaste的issue中，Snipaste的开发者分析认为是img2latex-mathpix 使用 JavaFX 读取剪贴板图像导致的问题。
参考 https://stackoverflow.com/questions/48932575/getting-image-from-clipboard-awt-vs-fx
@blaisewang 希望开发者能进一步解决该问题

**Comment by blaisewang** [comment]
> 在Snipaste的issue中，Snipaste的开发者分析认为是img2latex-mathpix 使用 JavaFX 读取剪贴板图像导致的问题。
> 参考 https://stackoverflow.com/questions/48932575/getting-image-from-clipboard-awt-vs-fx
> @blaisewang 希望开发者能进一步解决该问题

确实 JavaFX 有很多问题，而且也不是一个主流的图形库，至少从目前看来并不能满足这个 App 非常简单的需求。我已经考虑在用其他语言重写这个 App 了，来实现一些呼声较高但是由于 Java 语言本身限制做不到的 feature，比如 #94 ，可惜目前工作比较忙，还没时间
